version: "3.3"

services:
  php:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: php:8-apache
    working_dir: /var/www/html
    container_name: menke.production.testproject
    restart: always
    volumes:
      - storage:/var/www/html/storage
      - env:/envfile
      
volumes:
  env:
    external:
      name: menke.production.testproject.env
  storage:
    external:
      name: menke.production.testproject.storage

networks:
  default:
    external:
      name: nginx-proxy
