version: "3.3"

services:
  php:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: php:8-apache
    working_dir: /var/www/html
    container_name: menke.production.testproject
    restart: always
    ports:
      - "8081:80"
      - "8082:81"
      - "8083:443"
    volumes:
      - storage:/var/www/html/storage
      - env/.env:/var/www/html/.env
      
volumes:
  env:
    external:
      name: menke.production.testproject.env
  storage:
    external:
      name: menke.production.testproject.storage
