pipeline {
  agent any
  stages {
        stage('Stopping current container') {
          steps {
            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
              sh '''docker stop ${GROUP}.production.${PROJECT}
'''
              echo 'Stopped current staging container'
            }
          }
        }

        stage('Removing current container') {
          steps {
            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
              sh 'docker rm ${GROUP}.staging.${PROJECT}'
              echo 'Removed current staging container'
            }
          }
        }

    stage('Building') {
      steps {
        sh 'docker-compose --file ./docker/production/docker-compose.yml up -d --build'
        echo 'Completed successfully!'
      }
    }
    
   stage('Running composer update') {
      steps {
        sh 'docker exec ${GROUP}.production.${PROJECT} composer update '
      }
    }
  
    stage('Running composer install') {
      steps {
        sh 'docker exec ${GROUP}.production.${PROJECT} composer install '
      }
    }
   

  }
  environment {
    GROUP = 'menke'
    PROJECT = 'testproject'
  }
}
