version: "3.3"

services:
  php:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    image: php:8-apache
    working_dir: /var/www/html
    container_name: menke.staging.testproject.mysql
    restart: always
    ports:
      - "8081:80"
      - "8082:81"
      - "8083:443"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: menke.staging.testproject.mysql
    environment:
      - MYSQL_ROOT_PASSWORD=thisisareallystrongpassword123
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
