name: Superlinter

on:
  push:
    branches: [ ** ]
  pull_request:
    branches: [ ** ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Super-Linter
    uses: github/super-linter@v4.8.5
