name: Superlinter

on:
  - push
  - pull_request

jobs:
  Superlinter:
    name: Superlint for github
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Super-Linter
      uses: github/super-linter@v4.8.5
